export const enum REDUCER_ACTION_TYPE {
  OPEN_MINI_SIDEBAR,
  OPEN_CARTBAR,
  OPEN_MINI_NAVBAR,
  CLOSE_ALL_BARS,
  GET_PRODUCTS_BEGINS,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_ERROR,
  GET_FEATURED_PRODUCTS_BEGINS,
  GET_FEATURED_PRODUCTS_SUCCESS,
  GET_FEATURED_PRODUCTS_ERROR,
}
