export const featuredItems = [
  {
    id: "01",
    name: "Best selling Products",
    desc: "Speakers of many variaties",
    products: [
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0101",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0102",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0103",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0104",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0105",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0106",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0107",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0108",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0109",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0110",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0111",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0112",
      },
    ],
  },
  {
    id: "02",
    name: "Keezy Store Products",
    desc: "Speakers of many variaties",
    products: [
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0201",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0205",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0206",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0207",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0208",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0209",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0210",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0211",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0212",
      },
    ],
  },
  {
    id: "03",
    name: "Other Products",
    desc: "Speakers of many variaties",
    products: [
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0301",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0307",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0308",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0309",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0310",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0311",
      },
      {
        name: "iPhone 7 Plus",
        price: 20,
        url: "/",
        desc: "Best Phone Ever!",
        id: "0312",
      },
    ],
  },
];

export const sidebarItems = {
  mainItems: [
    {
      id: "0",
      name: "Featured Products",
      url: "/",
      selected: true,
      imageUrl: "www.logo",
    },
    {
      id: "1",
      name: "Phones",
      url: "/",
      selected: false,
      imageUrl: "www.logo",
    },
    {
      id: "2",
      name: "Laptops",
      url: "/",
      selected: false,
      imageUrl: "www.logo",
    },
    {
      id: "3",
      name: "Headsets/Earpiece",
      url: "/",
      selected: false,
      imageUrl: "www.logo",
    },
    {
      id: "4",
      name: "Watches",
      url: "/",
      selected: false,
      imageUrl: "www.logo",
    },
    {
      id: "5",
      name: "Others",
      url: "/",
      selected: false,
      imageUrl: "www.logo",
    },
  ],
  subItems: [
    {
      id: "01",
      name: "Apple Inc.",
      products: [
        { pid: "0101", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0104", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0105", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0106", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0107", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0108", pname: "MacBook Pro", purl: "/", pselected: false },
      ],
    },
    {
      id: "02",
      name: "Apple Inc.",
      products: [
        { pid: "0204", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0205", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0206", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0207", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0208", pname: "MacBook Pro", purl: "/", pselected: false },
      ],
    },
    {
      id: "03",
      name: "Apple Inc.",
      products: [
        { pid: "0301", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0302", pname: "MacBook Pro", purl: "/", pselected: false },
      ],
    },
    {
      id: "04",
      name: "Apple Inc.",
      products: [
        { pid: "0401", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0402", pname: "MacBook Pro", purl: "/", pselected: false },
        {
          pid: "0403",
          pname: "IPhone 14 Pro Max",
          purl: "/",
          pselected: true,
        },
        { pid: "0404", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0405", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0406", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0407", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0408", pname: "MacBook Pro", purl: "/", pselected: false },
      ],
    },
    {
      id: "05",
      name: "Apple Inc.",
      products: [
        { pid: "0501", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0502", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0503", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0504", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0505", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0506", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0508", pname: "MacBook Pro", purl: "/", pselected: false },
      ],
    },
    {
      id: "06",
      name: "Apple Inc.",
      products: [
        { pid: "0601", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0602", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0603", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0604", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0605", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0606", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0607", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0608", pname: "MacBook Pro", purl: "/", pselected: false },
      ],
    },
    {
      id: "07",
      name: "Apple Inc.",
      products: [
        { pid: "0701", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0702", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0703", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0704", pname: "MacBook Pro", purl: "/", pselected: false },
      ],
    },
    {
      id: "08",
      name: "Apple Inc.",
      products: [
        { pid: "0801", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0802", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0805", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0806", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0807", pname: "MacBook Pro", purl: "/", pselected: false },
        { pid: "0808", pname: "MacBook Pro", purl: "/", pselected: false },
      ],
    },
  ],
};
