import "../globals.css";

export const metadata = {
  title: "Keezy Accessories Studio",
  description: "Generated by Next, Typescript, Sanity & TailwindCSS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
